"""Implementation of the `zig_host_toolchain` repository rule."""

load("@zig_toolchains//private:toolchains.bzl", "ZIG_TOOLCHAINS")

_VERSION_ENV = "RULES_ZIG_HOST_SDK"

DOC = """\
Expose a registered Zig SDK for the host platform.

By default selects the first registered Zig SDK version, i.e. the default
toolchain version, or the latest if no default is set. Set the `{env}`
environment variable to a registered version to override.

Generates a `toolchain.bzl` file with a `zig_path(ctx)` function that resolves
the host platform's Zig binary from a repository_ctx or module_ctx.
""".format(env = _VERSION_ENV)

def host_platform(os_name, arch):
    """Map a `repository_ctx.os` name and arch to a Zig exec platform string.

    Args:
      os_name: The `repository_ctx.os.name` value, e.g. `"linux"`.
      arch: The `repository_ctx.os.arch` value, e.g. `"amd64"`.

    Returns:
      A `(error, platform)` tuple. `error` is `None` and `platform` a string
      like `"x86_64-linux"` on success, otherwise `error` holds a message and
      `platform` is `None`.
    """
    os_name = os_name.lower()
    if "linux" in os_name:
        os = "linux"
    elif "mac" in os_name or "darwin" in os_name:
        os = "macos"
    elif "windows" in os_name:
        os = "windows"
    else:
        return ("Unsupported host operating system: {}".format(os_name), None)

    if arch in ["amd64", "x86_64", "x64"]:
        cpu = "x86_64"
    elif arch in ["aarch64", "arm64"]:
        cpu = "aarch64"
    else:
        return ("Unsupported host CPU architecture: {}".format(arch), None)

    return (None, "{}-{}".format(cpu, os))

def select_host_zig(toolchains, platform, requested):
    """Pick the Zig SDK label for `platform` from `toolchains`.

    Args:
      toolchains: The `ZIG_TOOLCHAINS` list of `struct(version, exec_platform,
        zig)` records generated by `toolchains_repo.bzl`.
      platform: The host exec platform string, e.g. `"x86_64-linux"`.
      requested: The Zig SDK version to select, or a falsy value to select the
        first registered version for `platform`.

    Returns:
      A `(error, zig)` tuple. `error` is `None` and `zig` the selected `Label`
      on success, otherwise `error` holds a message and `zig` is `None`.
    """
    candidates = [
        toolchain
        for toolchain in toolchains
        if toolchain.exec_platform == platform
    ]
    if not candidates:
        return ("No registered Zig SDK supports the host platform '{}'.".format(platform), None)

    if not requested:
        return (None, candidates[0].zig)

    for toolchain in candidates:
        if toolchain.version == requested:
            return (None, toolchain.zig)

    return ("{} requested Zig SDK version '{}', which is not registered for host platform '{}'. Registered versions: {}.".format(
        _VERSION_ENV,
        requested,
        platform,
        [toolchain.version for toolchain in candidates],
    ), None)

def _zig_host_toolchain_impl(repository_ctx):
    error, platform = host_platform(repository_ctx.os.name, repository_ctx.os.arch)
    if error:
        fail(error)

    requested = repository_ctx.os.environ.get(_VERSION_ENV)
    error, zig = select_host_zig(ZIG_TOOLCHAINS, platform, requested)
    if error:
        fail(error)

    repository_ctx.file("BUILD.bazel", "")
    repository_ctx.file("toolchain.bzl", """\
# Generated by zig_host_toolchain.bzl

load("@rules_zig//zig/private/common:zig_cache.bzl", "env_zig_cache_prefix")

_ZIG = Label({zig})
_PLATFORM = {platform}

def zig_path(ctx):
    return ctx.path(_ZIG)

def zig_cache(ctx):
    return env_zig_cache_prefix(ctx.os.environ, _PLATFORM)
""".format(zig = repr(str(zig)), platform = repr(platform)))

zig_host_toolchain = repository_rule(
    _zig_host_toolchain_impl,
    doc = DOC,
    environ = [_VERSION_ENV],
)
